version: "3.8"

services:
  app:
    build: .
    container_name: history-app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=history_db
      - DB_SSLMODE=disable
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      # Монтируем папку с миграциями для доступа из контейнера
      - ./migrations:/app/migrations

  postgres:
    image: postgres:15-alpine
    container_name: history-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: history_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Удалили строку с init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d history_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
