// Twitch не публикует полный список запрещённых слов публично,
// поэтому этот словарь — практичный стартовый набор для антибуллинг-фильтра,
// собранный по категориям прямых оскорблений и токсичных фраз.
// Его удобно расширять вручную без правки логики фильтра.

export const antiBullyingDictionary = {
  metadata: {
    version: "1.0.0",
    localeSupport: ["ru", "en"],
    note: "Curated anti-bullying dictionary for direct insults and hostile phrases.",
  },
  phrases: {
    ru: [
      "ты даун",
      "ты дебил",
      "ты идиот",
      "ты придурок",
      "ты тупой",
      "ты тупая",
      "ты тупица",
      "ты уебок",
      "ты мудак",
      "ты мразь",
      "ты тварь",
      "ты урод",
      "ты ублюдок",
      "ты гнида",
      "ты сволочь",
      "ты чмо",
      "ты лох",
      "ты конченый",
      "ты конченая",
      "пошел нахуй",
      "иди нахуй",
      "сдохни",
      "чтоб ты сдох",
      "чтоб ты сдохла",
    ],
    en: [
      "you are an idiot",
      "you are stupid",
      "you are a moron",
      "you are a dumbass",
      "you are an asshole",
      "you piece of shit",
      "fuck you",
      "go to hell",
      "drop dead",
      "go kill yourself",
    ],
  },
  wordPrefixes: {
    ru: [
      "даун",
      "дебил",
      "идиот",
      "придур",
      "тупиц",
      "уеб",
      "еблан",
      "мудак",
      "мраз",
      "твар",
      "урод",
      "ублюд",
      "гнид",
      "сволоч",
      "чмо",
      "лох",
      "кончен",
      "нищеброд",
      "гандон",
      "шлюх",
      "сук",
      "пидорас",
      "мерзав",
      "подон",
      "скотин",
      "дрян",
    ],
    en: [
      "retard",
      "idiot",
      "moron",
      "dumbass",
      "asshole",
      "bastard",
      "bitch",
      "whore",
      "loser",
      "freak",
      "motherfucker",
      "scumbag",
      "dipshit",
      "jerk",
    ],
  },
};

export const flatBanwordsList = [
  ...antiBullyingDictionary.phrases.ru,
  ...antiBullyingDictionary.phrases.en,
  ...antiBullyingDictionary.wordPrefixes.ru,
  ...antiBullyingDictionary.wordPrefixes.en,
];
